random_seed: 112
grid:
  learning_rates: [0.1, 0.01]
  predict_days: [5]
  look_back_days: [15, 30, 45, 60, 90]
  architectures:
    # layer and the rest is its kwargs
    - - layer: lstm
        units: 400
    - - layer: lstm
        units: 200
    - - layer: lstm
        units: 100
    - - layer: lstm
        units: 400
        return_sequences: true
      - layer: drop_out
        rate: 0.2
      - layer: lstm
        units: 200
      - layer: dense_relu
        units: 64
    - - layer: lstm
        units: 200
        return_sequences: true
      - layer: drop_out
        rate: 0.2
      - layer: lstm
        units: 100
      - layer: dense_relu
        units: 64
    - - layer: lstm
        units: 400
        return_sequences: true
      - layer: drop_out
        rate: 0.2
      - layer: lstm
        units: 200
    - - layer: lstm
        units: 200
        return_sequences: true
      - layer: drop_out
        rate: 0.2
      - layer: lstm
        units: 100

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: "%(asctime)s.%(msecs)06d %(name)s %(levelname)s: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: default
      filename: "./log/%Y%m%d_%H%M%S.log"
      mode: a
  loggers:
    root:
      level: INFO
      handlers: [console, file]

time_zone: Australia/Adelaide
